_target_: dataset.OscarDataset
name: "allegro/polemo2-official-en"
language: ""
split: "train"
n_examples: ${exp.n_examples}
max_length: ${exp.max_length}
mlm_probability: 0.15
batch_size: ${exp.batch_size}
text_column: "source"
