_target_: dataset.SentenceClassificationDataset
name: "PL-MTEB/wikinews-pl-clustering-p2p"
split: "test"
n_classes: 9
max_length: ${exp.max_length}
batch_size: ${exp.batch_size}
n_examples: ${exp.n_examples_per_valid_dataset}
sentence_keys: 
  - "sentences"
label_key: "labels"
label_mapping: 
  "sport": 0
  "kultura_i_rozrywka": 1
  "polityka": 2
  "gospodarka": 3
  "społeczeństwo": 4
  "nauka": 5
  "katastrofy_i_klęski_żywiołowe": 6
  "prawo_i_przestępczość": 7
  "technika": 8