_target_: dataset.OscarDataset
name: "allegro/summarization-allegro-articles"
language: ""
split: "validation"
n_examples: ${exp.n_examples_per_valid_dataset}
max_length: ${exp.max_length}
mlm_probability: 0.15
batch_size: ${exp.batch_size}
text_column: "source"
