_target_: dataset.PairScoreDataset
name: "sentence-transformers/all-nli"
split: "train"
use_rows: 0.01 # either a float between 0 and 1 or an integer
max_length: ${exp.max_length}
batch_size: ${exp.batch_size}
loss_fn:
  _target_: sentence_transformers.losses.CosineSimilarityLoss
  model:
    _target_: torch.nn.Identity