_target_: dataset.PairDataset
name: "sentence-transformers/gooaq"
split: "train"
max_length: ${exp.max_length}
batch_size: ${exp.contrastive_batch_size}
query_column: "question"
answer_column: "answer"
loss_fn:
  _target_: sentence_transformers.losses.MultipleNegativesRankingLoss
  model:
    _target_: torch.nn.Identity