_target_: dataset.SentenceClassificationDataset
name: "allegro/klej-psc"
split: "test"
n_classes: 2
n_examples: ${exp.n_examples_valid}
max_length: ${exp.max_length}
batch_size: ${exp.batch_size}
sentence_keys: 
  - "extract_text"
  - "summary_text"
label_key: "label"