_target_: models.ILKTModel
config: 
  _target_: models.ILKTConfig
  backbone_config:
    pretrained_model_name_or_path: ${exp.pretrained_model_name_or_path}
    trust_remote_code: true
  embedding_head_config:
    pool_type: "cls"
  mlm_head_config: {}
