_target_: models.ILKTModel
config: 
  _target_: models.ILKTConfig
  backbone_config:
    pretrained_model_name_or_path: ${exp.pretrained_model_name_or_path}
    trust_remote_code: true
    torch_dtype: torch.bfloat16
  embedding_head_config:
    pool_type: "cls"
    normalize_embeddings: true
  mlm_head_config:
    n_dense: 0
    use_batch_norm: true
    use_layer_norm: false
    dropout: 0.0
  cls_head_config:
    pool_type: "cls"
    n_dense: 0
    use_batch_norm: true
    use_layer_norm: false
    dropout: 0.0
  cls_heads: []
