_target_: dataset.TripletDataset
name: "sentence-transformers/quora-duplicates"
split: "train"
n_examples: ${exp.n_examples}
max_length: ${exp.max_length}
batch_size: ${exp.batch_size}
loss_fn:
  _target_: sentence_transformers.losses.TripletLoss
  model:
    _target_: torch.nn.Identity