_target_: dataset.OscarDataset
name: "teddy-f-47/wikipedia_pl_20231201"
language: ""
split: "train"
n_examples: ${exp.n_examples}
max_length: ${exp.max_length}
mlm_probability: 0.15
batch_size: ${exp.batch_size}
text_column: "text"
