# train_config.yaml

defaults:
  - _self_
  - model: starter
  - train_datasets:
    - contrastive/all-nli/all-nli-pair-score.yaml
    - contrastive/msmarco-msmarco-distilbert-base-tas-b/msmarco-msmarco-distilbert-base-tas-b-triplet.yaml
    - contrastive/stsb/stsb.yaml

exp:
  log_dir: # set during runtime to automatically created dir
  pretrained_model_name_or_path: microsoft/mdeberta-v3-base
  max_length: 256
  batch_size: 32
  seed: 42
  training_steps: 40_001
  n_examples: 20_000
  n_examples_valid: 10_000
  validate_every: 10_000
  save_every: 10_000
  optimizer:
    opt: "adam"
    lr: 2e-5
    weight_decay: 0.0
    filter_bias_and_bn: true

fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  accelerator: "cuda"

wandb:
  project: "inter-lingual_knowledge_transferring_in_NLP_embeddings"
  entity: "top-notch-nlp"
