_target_: dataset.SentenceClassificationDataset
name: "allegro/klej-psc"
split: "train"
n_classes: 2
max_length: ${exp.max_length}
batch_size: ${exp.batch_size}
sentence_keys: 
  - "extract_text"
  - "summary_text"
label_key: "label"