_target_: dataset.SentenceClassificationDataset
name: "allegro/klej-dyk"
split: "test"
n_classes: 2
n_examples: ${exp.n_examples_valid}
max_length: ${exp.max_length}
batch_size: ${exp.batch_size}
sentence_keys: 
  - "question"
  - "answer"
label_key: "target"