_target_: dataset.OscarDataset
name: "oscar-corpus/OSCAR-2109"
language: "deduplicated_pl"
split: "train"
n_examples: ${exp.n_examples}
max_length: ${exp.max_length}
mlm_probability: 0.15
batch_size: ${exp.batch_size}