_target_: dataset.SentenceClassificationDataset
name: "PL-MTEB/scifield"
split: "test"
n_classes: 5
max_length: ${exp.max_length}
batch_size: ${exp.batch_size}
n_examples: ${exp.n_examples_per_valid_dataset}
sentence_keys: 
  - "text"
label_key: "label"