_target_: dataset.TripletDataset
name: "sentence-transformers/msmarco-distilbert-margin-mse-sym-mnrl-mean-v1"
split: "train"
n_examples: ${exp.n_examples}
max_length: ${exp.max_length}
batch_size: ${exp.batch_size}
query_col_name: "query"
positive_col_name: "positive"
negative_col_name: "negative"
subset: "triplet"
loss_fn:
  _target_: sentence_transformers.losses.TripletLoss
  model:
    _target_: torch.nn.Identity